# Generated by Django 6.0.4 on 2026-04-13 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_client_caoch_client_coach_client_created_at_and_more'),
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessplan',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitness_plans', to='accounts.coach'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessplan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_plans', to='accounts.client'),
        ),
    ]
